apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache
  namespace: apache
spec:
  scaleTargetRef:  #kis chiz ko scale krna hai means pod ko, replica set, deployment ko..
    kind: Deployment
    name: apache-deployment
    apiVersion: apps/v1

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5   #ye 5 ho jaye toh replica bna do
